### ISSUE TITLE
Request: No need to confirm when moving a single consumable

### ISSUE THREAD

**Issue by DrPippin** [dasilva333/DIM#41]
Request for app functionality (I'm using iOS):

When moving an item that can be grouped in stacks, such as a heavy ammo synthesis or spinmetal, I would request that if there is only one item in the stack you are moving that you do not display the pop up window/require hitting transfer.

**Comment by dasilva333** [comment]
Great idea expect it in the next version

**Comment by dasilva333** [comment]
fixed in 1.6.4 please confirm and close ticket

**Comment by DrPippin** [comment]
1.6.4 is still asking for confirmation of how many to move when there's only one in the stack. I tried with a heavy ammo synthesis, a pulse rifle telemetry, and a spinmetal - all of which are still showing the pop up for confirmation to transfer 1.

**Comment by dasilva333** [comment]
Try 1.6.5 instead. 1.6.4 was built several times and you might be using a revision with the fix. Thanks for testing this

**Comment by DrPippin** [comment]
Works!! Thanks!
